#!/bin/bash
# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title open-proweb
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🤖

# Documentation:
# @raycast.description 打开proweb
# @raycast.author jason_ji
# @raycast.authorURL https://raycast.com/jason_ji
cursor /Users/jasonj/Nextcloud/国泰君安/工作/code/vintex-submit-web